---
- name: Remediate TLS Compliance Issue
  hosts: all
  become: yes
  tasks:
    - name: Check apache config syntax
      ansible.builtin.command: apachectl configtest
      register: apache_configtest
      ignore_errors: true

    - name: Print apache configtest
      ansible.builtin.debug:
        var: apache_configtest
