---
all:
  vars:
    ansible_user: root
    ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
    ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no"
    demo_domain: app-demo.example.com
    tls_cert_path: /etc/pki/tls/certs/demo.crt
    tls_key_path: /etc/pki/tls/private/demo.key
    backend_port: 443
    lb_host: <LB_IP_HERE>

  children:
    backends:
      children:
        patched:
        control:

    patched:
      hosts:
        rhel-patched:
          ansible_host: 10.46.253.221

    control:
      hosts:
        rhel-control:
          ansible_host: 10.46.250.70

    satellite:
      hosts:
        red-hat-satellite:
          ansible_host: 10.46.253.59
